### ISSUE TITLE
Usability Test – Beta Homepage

### ISSUE THREAD

**Issue by colinmurphy01** [usdoj-crt/beta-ada#19] opened 2021-03-28 21:07 UTC
### Context
With the beta homepage template and updated content in a prototype environment, we are ready to get feedback on it.

### This issue is done when
- [ ] Plan
- [ ] Protocol
- [ ] Recruitment
- [ ] Scheduling/Sessions
- [ ] Analysis

**Comment by lauraponce** [comment] 2021-03-29 17:58
Duplicate of #44 & #45

**Closed** 2021-03-29 17:58 UTC
Labels: Epic, Research
